######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 6 14:31:22 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h NbPartikel.h scene.h
FORMS += gui.ui
SOURCES += gui.cpp main.cpp NbPartikel.cpp scene.cpp
