######################################################################
# Automatically generated by qmake (2.01a) Fr. Okt 7 02:07:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h NbPartikel.h NbVis.h scene.h
FORMS += gui.ui
SOURCES += gui.cpp main.cpp NbPartikel.cpp NbVis.cpp scene.cpp
