######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 6 13:22:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h
FORMS += gui.ui
SOURCES += gui.cpp main.cpp
